[project]
name = "mem0-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "mem0ai>=0.1.55",
    "PyYAML>=6.0",
    "starlette>=0.46.0",
    "uvicorn>=0.34.0",
]

[tool.setuptools.packages.find]
include = ["mem0_mcp*"]
